// Generated by CoffeeScript 2.4.1
var draw, mousePressed, setup, value;

value = 0.2;

setup = function() {
  return createCanvas(200, 200);
};

draw = function() {
  return bg(value);
};

mousePressed = function() {
  return value = 1 - value;
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsSUFBQSxFQUFBLFlBQUEsRUFBQSxLQUFBLEVBQUE7O0FBQUEsS0FBQSxHQUFROztBQUVSLEtBQUEsR0FBUSxRQUFBLENBQUEsQ0FBQTtTQUNQLFlBQUEsQ0FBYSxHQUFiLEVBQWlCLEdBQWpCO0FBRE87O0FBRVIsSUFBQSxHQUFPLFFBQUEsQ0FBQSxDQUFBO1NBQ04sRUFBQSxDQUFHLEtBQUg7QUFETTs7QUFHUCxZQUFBLEdBQWUsUUFBQSxDQUFBLENBQUE7U0FDZCxLQUFBLEdBQVEsQ0FBQSxHQUFJO0FBREUiLCJzb3VyY2VzQ29udGVudCI6WyJ2YWx1ZSA9IDAuMlxyXG5cclxuc2V0dXAgPSAtPlxyXG5cdGNyZWF0ZUNhbnZhcyAyMDAsMjAwXHJcbmRyYXcgPSAtPlxyXG5cdGJnIHZhbHVlXHJcblxyXG5tb3VzZVByZXNzZWQgPSAtPlxyXG5cdHZhbHVlID0gMSAtIHZhbHVlIl19
//# sourceURL=c:\github\CD_Tim\shortcut\coffee\sketch.coffee